### ISSUE TITLE
Too many questions

### ISSUE THREAD

**Issue by demidovakatya** [demidovakatya/imaginaryfriend#10]
> Понизить вероятность вопросительного знака.
> Нужно хотя бы подогнать её под реальное распределение знаков пунктуации, а то много утвердительных предложений с вопросительным знаком выходит.

**Comment by demidovakatya** [comment]
https://github.com/demidovakatya/imaginaryfriend/blob/master/src/domain/pair.py#L18

@REDNBLACK плизики зафигачь сегодня
посмотрим

**Comment by REDNBLACK** [comment]
Вроде должно было стать получше.

**Comment by REDNBLACK** [comment]
Стало или нет? 🤔
Лично я улучшения не заметил

**Comment by REDNBLACK** [comment]
Вроде все ок
