### ISSUE TITLE
Don't repeat phrases

### ISSUE THREAD

**Issue by demidovakatya** [demidovakatya/imaginaryfriend#11]
короче, когда бот узнает фразу, все слова в которой ему не были знакомы ранее, он её тупо повторяет:

— шла Саша по шоссе
— Шла саша по шоссе.

бесит это.
думаю, в случаях когда бот ваще-ваще всё новое узнал, ему будет мудрее промолчать

— шла Саша по шоссе
— [тишина — т.к. только узнал слова]
— шла Александра по хайвею
— Шла саша по хайвею! 
— по дороге из жёлтого кирпича
— По шоссе?

**Comment by REDNBLACK** [comment]
Добавил примитивную проверку, теперь не будет повторять.
