### ISSUE TITLE
Implement special triggers with random chance

### ISSUE THREAD

**Issue by REDNBLACK** [demidovakatya/imaginaryfriend#16]
Мапа вида - 
```
{
     'nickname человека': Object {
        'reaction_type': 'message/sticker',
        'value': 'собственно id стикера или сообщение',
        'chance': '1-50'
    }
}
```

**Comment by REDNBLACK** [comment]
лучше сделать шанс фиксированным в 1, как никак "special" trigger.

**Comment by demidovakatya** [comment]
хм, хорошая идея

**Comment by demidovakatya** [comment]
а что от меня требуется? :)

**Comment by REDNBLACK** [comment]
Будет настраиваться командой, доступной только админам.

**Comment by REDNBLACK** [comment]
БД: Redis

Команды: 
`/trigger @user_link reaction_type(m/s) message/sticker_id(id можно получить через @getStickerId_bot) Дата и время в формате DD-MM-YYYY|H:i(опционально, для одноразового триггера с шансом в 100%)` - Добавить реакцию
`/trigger @user_link d` - Удалить реакцию

Примеры:
`/trigger @REDNBLACK m Привет, REDNBLACK!`
`/trigger @demidovakatya s BQADAgADZwQAAjbsGwXZJSFa025tBwI`
`/trigger @future m Привет из будущего! 01.01.2029|01:00`
`/trigger @REDNBLACK d`

**Comment by REDNBLACK** [comment]
Useless
