### ISSUE TITLE
Implement links, photos and videos analysis for uniqueness

### ISSUE THREAD

**Issue by REDNBLACK** [demidovakatya/imaginaryfriend#17]
Если в течение дня, уже была такая ссылка - кидать стикер с баяном.

**Comment by sanex3339** [comment]
+

**Comment by REDNBLACK** [comment]
БД: Redis
На один чат хранится 100 ссылок максимум, каждая истекает через 8 часов.
Отсылать будет случайный стикер из списка в конфиге.
Сравнение ссылок самое примитивное, две последних части hostname + path + fragment.

**Comment by REDNBLACK** [comment]
Стикер пока лишь один, нужна новая система хранения настроек.

**Comment by REDNBLACK** [comment]
Добавить также анализ ID фото и видео файлов, если такой ID уже был в течение 8 часов - кидать стикер с баяном

**Comment by REDNBLACK** [comment]
Также добавить проверку приватный ли это чат (нет смысла проверять ссылки)

**Comment by REDNBLACK** [comment]
Анализ видео и аудио невозможен, на один и тот же файл возвращаются разные ID.
Сделал только для фоток.
