### ISSUE TITLE
Replace SQL with Redis/Google Ngrams/similar

### ISSUE THREAD

**Issue by REDNBLACK** [demidovakatya/imaginaryfriend#19]
^ title

**Comment by demidovakatya** [comment]
вроде готово?

**Comment by REDNBLACK** [comment]
Не, даже не начинал

**Comment by REDNBLACK** [comment]
Возможно не стоит делать на Redis, из-за следующих минусов:

1. Практически невозможно модерировать слова
2. Со временем, потребление памяти вырастет в разы
3. Не понятно, как составлять score для слов/фраз/последовательностей

**Comment by REDNBLACK** [comment]
Придется вернуть старый алгоритм формирования триграм, старый вариант был намного лучше.
Команду moderate возможно реализовать с помощью redis.scan
Для команды get_stats придется вести отдельный ключ stats:chat_id с инкрементом

**Comment by REDNBLACK** [comment]
Переключил обратно на SQL с Redis.

**Comment by REDNBLACK** [comment]
Фух... Почти все готово. Осталось улучшить логику ReplyGenerator и можно переезжать на редис :)

**Comment by REDNBLACK** [comment]
Перенес данные и переключил на redis

**Comment by REDNBLACK** [comment]
Бот проглатывает последнее слово, нужен фикс ReplyGenerator.
