### ISSUE TITLE
Add /borscht command

### ISSUE THREAD

**Issue by tefimov** [demidovakatya/imaginaryfriend#23]
Borscht is the cornerstone component of warm relationships between two people, and that is why it is very important for ImaginaryFriend to have an ability to share tasty borscht with fellow chatters.

![image](https://cloud.githubusercontent.com/assets/3992246/20743861/66f55e6a-b6fa-11e6-902b-74290d4209bc.png)

**Comment by REDNBLACK** [comment]
Наверни борщеца! /borscht

**Comment by demidovakatya** [comment]
сделал же

**Comment by tefimov** [comment]
Delicious! Very tasty! :3
