### ISSUE TITLE
Add suggestions for new commands 

### ISSUE THREAD

**Issue by demidovakatya** [demidovakatya/imaginaryfriend#24]
Подсказки, в общем, чтобы было проще набирать.

**Comment by REDNBLACK** [comment]
они ведь временные...

**Comment by demidovakatya** [comment]
Потом можно будет удалить. Я в README.md добавила описание. Как перенесём фичи — выпилим и описание, и команды.
:3

**Comment by REDNBLACK** [comment]
ok then

**Comment by REDNBLACK** [comment]
Done.
