### ISSUE TITLE
improve /moderate a little

### ISSUE THREAD

**Issue by demidovakatya** [demidovakatya/imaginaryfriend#29]
```
> /moderate разнооб
< - разнообразия : 3295
> /moderate разнообразия 3295
// удалено
```

очень долго вбивать.
предлагаю так:

```
> /moderate разнооб
< - разнообразия : 3295
> /moderate 3295
// удалено
```

но чтобы не возникало конфликтов с «словами» вида `2016`, может быть сделаем:

```
> /words разнооб
< - разнообразия : 3295
> /delete 3295
// удалено
```

**Comment by REDNBLACK** [comment]
'/moderate слово' - поиск слова (для поиска слова состоящего только из числ, необходимо обернуть в кавычки)
'/moderate ID слова' - удаление слова с таким ID

**Comment by demidovakatya** [comment]
спасибо!
