### ISSUE TITLE
Remove URLs 

### ISSUE THREAD

**Issue by demidovakatya** [demidovakatya/imaginaryfriend#30]
Воображаемый друг сжирает урлы, причём как-то не очень адекватно.

Пример:
> У нас на матмехе лекции ведёт😂 однажды пригласил пахома на лекцию h ttps://m.youtube.com/watch?v=kovbe5ikghq.
> **h ttps://m.youtube.com/watch?v=kovbe5ikghq**

Лучше всего их сразу убирать вообще тогда, например, этой регулярочкой:

```python
regex_url = re.compile(r'https?://[^\s]*')
text = regex_url.sub(' ', text)
```

@REDNBLACK, вопрос: не пошатает ли это никакие функции?

**Comment by REDNBLACK** [comment]
URL попала в базу до фикса с очисткой, сейчас это уже не нужно.
Из базы почистил.

**Comment by demidovakatya** [comment]
Больше не должны попадаться?

**Comment by REDNBLACK** [comment]
Да
