### ISSUE TITLE
Не удается найти слово через /moderate

### ISSUE THREAD

**Issue by eigenein** [demidovakatya/imaginaryfriend#32]
Чат `-1001087744178`:

> @ImaginaryFriend: В одс. Тоже хочу узнать, тем более про софт.
> /moderate одс
> @ImaginaryFriend: No words found!
> /moderate одс.
> @ImaginaryFriend: No words found!

**Comment by REDNBLACK** [comment]
Хм, интересно, спасибо за тикет.

Насчет разделения на две отдельных команды я не уверен, гораздо проще иметь одну.
Тем более в ридми описано, что для поиска numeric-слов, нужно заключать их в кавычки.

**Comment by REDNBLACK** [comment]
Сделал временный хак, посмотрим как будет работать

**Comment by demidovakatya** [comment]
still doesn't work

**Comment by REDNBLACK** [comment]
It should work now

**Comment by REDNBLACK** [comment]
Теперь новая система:
/mod_f слово - для поиска слов со startsWith совпадением
/mod_d слово - для удаления слова с полным совпадением

Прошу протестить, если будет возможность
