### ISSUE TITLE
Implement /vzhuh command

### ISSUE THREAD

**Issue by REDNBLACK** [demidovakatya/imaginaryfriend#33]

**Comment by demidovakatya** [comment]
Есть идея для улучшения: вместо `/vzhuh вжух и текст` – `/vzhuh и текст`. Так естественнее же, меня всё время подмывает написать именно `/вжух и аняня мимими` :)

**Comment by REDNBLACK** [comment]
Осталось улучшить алгоритм центрирования/отрисовки текста

**Comment by witzawitz** [comment]
У меня перестал работать vzhuh во всех чатиках. Ждём возвращения с нетерпением!

**Comment by REDNBLACK** [comment]
Fixed

**Comment by witzawitz** [comment]
Спасибо!
