### ISSUE TITLE
[Discussion] slowpoke reply to pictures

### ISSUE THREAD

**Issue by demidovakatya** [demidovakatya/imaginaryfriend#34]
1. если форварднуть картинку (некоторые используют форвард в тот же чатик вместо реплая), воображаемый друг шлёт слоупока,
2. если прислать такую же (или *ту же*, но во второй раз) картинку, то воображаемый друг не шлёт слоупока.

Такое поведение выглядит нелогичным. 

Я бы убрала этот ответ на картинки вообще. @REDNBLACK, что скажешь?

**Comment by demidovakatya** [comment]
relevant: #17

**Comment by REDNBLACK** [comment]
1. Легко пофиксить, сделаю сегодня
2. Странно, надо проверить

p.s: Если не удастся пофиксить, то уберем.
