### ISSUE TITLE
Фразы часто заканчиваются на предлог

### ISSUE THREAD

**Issue by eigenein** [demidovakatya/imaginaryfriend#35]
Привет!

Бот стал слишком часто заканчивать свои реплики на предлог. Кажется, это наблюдается в последние дни. Пример (чат `-193186456`):

> eigenein: Чо-то бот стал уж странно заканчивать фразы на предлог. Это не норма.
> ImaginaryFriend: Чо-то бот стал уж странно заканчивать фразы на!

**Comment by REDNBLACK** [comment]
See https://github.com/demidovakatya/imaginaryfriend/issues/19#issuecomment-269370793
