### ISSUE TITLE
Бот отправляет статус typing вне зависимости от наличия ответа

### ISSUE THREAD

**Issue by eigenein** [demidovakatya/imaginaryfriend#36]
Привет!

Не приоритетная мелочь: если боту нечего ответить, он все равно отправляет статус (typing), который висит дефолтные 5 секунд. Мне кажется, что хорошо бы либо не отправлять этот статус, либо сделать его значительно короче (например, секунду).

**Comment by REDNBLACK** [comment]
Нет возможности обнулить статус или сделать его короче.
Предлагаю либо добавить отправку рандомного сообщения из списка подготовленных, либо пока оставить как есть.

**Comment by eigenein** [comment]
Пожалуй, тогда лучше оставить как есть.

**Comment by REDNBLACK** [comment]
Ок, пока оставляем как есть.
