### ISSUE TITLE
Добавить поддержку utf8 для /vzhuh

### ISSUE THREAD

**Issue by witzawitz** [demidovakatya/imaginaryfriend#39]
<img width="422" alt="screenshot 2017-02-03 15 26 18" src="https://cloud.githubusercontent.com/assets/1055825/22591387/b3f96b14-ea2d-11e6-9e4a-417be1f76a59.png">

<img width="392" alt="screenshot 2017-02-03 15 28 00" src="https://cloud.githubusercontent.com/assets/1055825/22591396/bed13116-ea2d-11e6-8744-a4f1e4c925ee.png">

**Comment by dmitriigriazin** [comment]
Не трифорсит!

**Comment by REDNBLACK** [comment]
У шрифта нет поддержки юникода, не знаю что тут можно сделать.

**Comment by witzawitz** [comment]
Можно подключить шрифт с utf8? Могу помочь, как-то делала генирилку картинок со шрифтами.

**Comment by demidovakatya** [comment]
@bagza ньюфаги не умеют трифорсить ¯\_(ツ)_/¯

@witzawitz о, будет очень круто!
ждём пулл-реквест, стало быть? :)

**Comment by REDNBLACK** [comment]
![test-out](https://cloud.githubusercontent.com/assets/1498939/25072111/d82cb2a4-22cf-11e7-9d8c-a2951c65f677.png)
Так как помогать никто не хотел, пофиксил это сам. Enjoy.
