### ISSUE TITLE
Ручная чистка неугодных слов прямо из чатика

### ISSUE THREAD

**Issue by demidovakatya** [demidovakatya/imaginaryfriend#4]

**Comment by REDNBLACK** [comment]
Чистка будет производиться непосредственно из того чата, где пользователь является админом.
Чистить можно будет только свой чат, поиск будет производиться по словам (starts_with совпадение).

**Comment by REDNBLACK** [comment]
Надеюсь получится с inline-режимом

**Comment by REDNBLACK** [comment]
Базовая версия готова, хотелось бы реализацию, когда команды модерации не видны остальным людям в чатике.

**Comment by demidovakatya** [comment]
годно. а вообще можно сделать так, чтобы сообщения не было видно?

**Comment by REDNBLACK** [comment]
К сожалению, api не позволяет передавать в inline режиме id чатика.
Так что улучшить пока невозможно.
