### ISSUE TITLE
Implement `/o` command

### ISSUE THREAD

**Issue by demidovakatya** [demidovakatya/imaginaryfriend#44]
```
user: /o
[bot sends a picture with facepalm]
```

**Comment by REDNBLACK** [comment]
and \o
[bot sends a picture with hitler]

**Comment by demidovakatya** [comment]
не всегда корректно подбирает пикчу:

![image](https://user-images.githubusercontent.com/5788652/28547993-2c719958-70da-11e7-8430-fd6fdbb0d763.png)

**Comment by demidovakatya** [comment]
впрочем, кмк, это уже проблема сервиса
