### ISSUE TITLE
Автоматическая чистка базы

### ISSUE THREAD

**Issue by demidovakatya** [demidovakatya/imaginaryfriend#5]
при кике из комнаты через определённый промежуток времени

**Comment by REDNBLACK** [comment]
12 часов

**Comment by REDNBLACK** [comment]
При добавлении обратно - задача на очистку убирается из очереди.

**Comment by REDNBLACK** [comment]
Думаю стоит создать отдельную таблицу с Job'ами, чтоб при перезапуске бота ничего не терялось.

**Comment by REDNBLACK** [comment]
В приватных чатах, нет возможности узнать, что пользователь остановил бота и/или закрыл чат.
Надо что-то придумать.

**Comment by REDNBLACK** [comment]
Well... https://stackoverflow.com/questions/35263618/how-can-i-detect-whether-a-user-deletes-the-telegram-bot-chat

Закрываю до лучших времен...
