### ISSUE TITLE
Puctuation != words

### ISSUE THREAD

**Issue by demidovakatya** [demidovakatya/imaginaryfriend#7]
Не надо, чтобы бот запоминал `Молодец)`. Слова нужно чистить от пунктуации.

**Comment by demidovakatya** [comment]
https://github.com/demidovakatya/imaginaryfriend/blob/master/src/domain/pair.py#L19 
maybe

**Comment by REDNBLACK** [comment]
Надо чистить слова от любой пунктуации.

**Comment by REDNBLACK** [comment]
заодно почистить базу.

**Comment by demidovakatya** [comment]
чистить слова не от любой пунктуации, а от всей пунктуации, кроме `,-:`.
`?!.` — конец предложения.

**Comment by demidovakatya** [comment]
https://github.com/demidovakatya/imaginaryfriend/commit/9619c1d5a10371d95f4628bc0ea8ac0f54b58990
`all=.!?;()\-—"[]{}«»/*&^#$`

@REDNBLACK, сработает?

**Comment by REDNBLACK** [comment]
Вроде теперь работает, осталось почистить базу

**Comment by REDNBLACK** [comment]
база почищена
